--SELECT CG.NCC,CG.CODECOMMUNE,CM.Population99,CM.surface FROM COG CG ,COMMUNE CM WHERE CL='4' AND CM.codeInsee LIKE CG.codeCommune+'%';
SELECT CG.NCC,CG.CODECOMMUNE,CM.Population99,CM.surface FROM COG CG LEFT JOIN COMMUNE CM ON CG.CL='4' AND CM.codeInsee LIKE CG.codeCommune+'%';
